services:
  allure:
    container_name: allure
    image: "frankescobar/allure-docker-service"  # Используем официальный образ Allure Docker Service
    environment:
      CHECK_RESULTS_EVERY_SECONDS: 1  # Проверяем результаты каждые 1 секунду
      KEEP_HISTORY: 1  # Сохраняем историю отчетов
    ports:
      - "5050:5050"  # Порт для сервера отчетов Allure
      
  allure-ui:
    image: "frankescobar/allure-docker-service-ui"  # Используем официальный образ Allure UI
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "http://localhost:5050"
    ports:
      - "5252:5252"  # Порт для UI интерфейса
    
  app:
    depends_on:
      - allure # Запуск после старта сервера
    build:
      context: $PWD
      dockerfile: Dockerfile



